app: 
  image:
    repository: 
    tag: 
  appconfig:
    httpport: 9080
    httpsport: 9443
    MANUFACTURE_WORKORDER_URL: http://supplierdomain-service/supplierdomain/supplier/purchase/
    MANUFACTURE_USER: 
    MANUFACTURE_PASSWORD: 
  dbconfig:
    host: 
    user: 
    password: 
    schema: 
  scale:
    minReplica: 1
    maxReplicas: 3
  azureconfig:
    resourcegroup: 
    loadbalancerip: 
