app: 
  image:
    repository: novatec/technologyconsulting-showcase-orderdomain
    tag: 
  appconfig:
    httpport: 9080
    httpsport: 9443
    MANUFACTURE_WORKORDER_URL: http://supplierdomain-service/supplierdomain/supplier/purchase/
    MANUFACTURE_USER: admin
    MANUFACTURE_PASSWORD: adminpwd
  dbconfig:
    host: 
    port: "5432"
    user: 
    password: 
    schema: 
    name:
  scale:
    minReplica: 1
    maxReplicas: 3
  networking:
    ingressfqdn:
  azureconfig:
    resourcegroup: 
    loadbalancerip: 